name: Generated APK AAB (Clean)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clean all artifacts
        uses: c-hive/gha-remove-artifacts@31a76a8d9acac10c14de1892e21281e07b04e6d4
        with:
          age: '60 seconds' 
